name: Test Code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to miclem
        run: echo "Hello Miclem"